# npm i docker-compose
# cd docker
# docker-compose up
# go to mysql workbench and log in
services:
 db:
   image: mysql:latest
   restart: always
   container_name: beautifulFlyingDogs
   ports:
     - "3307:3306" # host port : container port
   environment:
     MYSQL_ROOT_PASSWORD: rootpasswordfornerds9001
     MYSQL_DATABASE: luxuper_db
     MYSQL_USER: usr
     MYSQL_PASSWORD: usrpass9000
   volumes:
     - ./mysql_data:/var/lib/mysql